// generated by codegen/codegen.py, remove this comment if you wish to edit this file
/**
 * This module provides a hand-modifiable wrapper around the generated class `DiscardStmt`.
 */

private import codeql.swift.generated.stmt.DiscardStmt

class DiscardStmt extends Generated::DiscardStmt { }
